import { useEffect,useEffectEvent,useRef,useState } from 'react';
import { Radio,Type,Plus,Trash2,ArrowUp,ArrowDown,Copy,Check,ExternalLink,Play,Pause,RotateCcw,Download,SlidersHorizontal,Sparkles,Monitor,AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { NativeSelect } from '@/components/ui/native-select';
import { DEFAULT_CONFIG,validateConfig } from '../lib/config.mjs';
import { STYLES,ANIMATIONS,presetSettings } from '../lib/styles.mjs';
import { type Config,buildLayers,drawFrame,loadFont } from '../lib/render';
import { canvasBlob,downloadBlob,exportAnimation } from '../lib/export';
import Preview from './preview';
import { LANGUAGES,translate } from '../lib/i18n.mjs';
function Range({label,value,min,max,step=1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(v:number)=>void}){return <div className="range-field"><div><span>{label}</span><output>{Number(value.toFixed(2))}{unit}</output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/></div>;}
export default function Studio(){
 const [config,setConfig]=useState<Config>(structuredClone(DEFAULT_CONFIG)),[loaded,setLoaded]=useState(false),[connected,setConnected]=useState(false),[status,setStatus]=useState('loading'),[error,setError]=useState(''),[paused,setPaused]=useState(false),[restart,setRestart]=useState(0),[active,setActive]=useState(0),[backdrop,setBackdrop]=useState('checker'),[copied,setCopied]=useState(false),[busy,setBusy]=useState(''),[progress,setProgress]=useState(0),[notice,setNotice]=useState(''),[captureKey,setCaptureKey]=useState('green'),[opening,setOpening]=useState(false);
 const pending=useRef<Config|null>(null),saving=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),exportAbort=useRef<AbortController|null>(null),latest=useRef(config);
 const t=(key:string)=>translate(key,config.language);
 useEffect(()=>{document.documentElement.lang=config.language;document.title='Typecast Studio';},[config.language]);
 const link=location.origin+'/overlay';
 function edit(patch:Partial<Config>){const next={...latest.current,...patch};latest.current=next;pending.current=next;setConfig(next);setStatus('editing');setError('');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(flush,550);}
 async function flush(){if(saving.current||!pending.current)return;const snapshot=pending.current;pending.current=null;saving.current=true;setStatus('saving');try{const response=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot),signal:AbortSignal.timeout(7000)}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||t("无法保存修改。"));setStatus(pending.current?'editing':'synced');setError('');}catch(e){if(!pending.current)pending.current=snapshot;setStatus('error');setError(e instanceof Error?t(e.message):t("无法同步设置。"));}finally{saving.current=false;if(pending.current)timer.current=setTimeout(flush,2000);}}
 useEffect(()=>{const source=new EventSource('/api/events');source.onmessage=e=>{try{const state=JSON.parse(e.data);setConnected(true);setLoaded(true);if(!pending.current&&!saving.current){setConfig(state.config);latest.current=state.config;setStatus('synced');}}catch{setError("无法读取设置。");}};source.onerror=()=>{setConnected(false);};const guard=(e:BeforeUnloadEvent)=>{if(pending.current||saving.current){e.preventDefault();}};window.addEventListener('beforeunload',guard);return()=>{source.close();if(timer.current)clearTimeout(timer.current);window.removeEventListener('beforeunload',guard);exportAbort.current?.abort();};},[]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(id);},[notice]);
 const externalEdit=useEffectEvent((lines:string[])=>edit({lines}));
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const tools=[{name:'get_overlay_settings',description:translate("读取当前直播文案和固定输出链接。"),inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({config:latest.current,url:link})},{name:'update_overlay_text',description:translate("替换直播文案，并加入自动同步队列。"),inputSchema:{type:'object',properties:{lines:{type:'array',items:{type:'string',maxLength:160},minItems:1,maxItems:8}},required:['lines'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const clean=validateConfig({...latest.current,lines:(input as {lines?:unknown})?.lines});externalEdit(clean.lines);return{status:'queued',lines:clean.lines};}}];for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[link]);
 function lineChange(index:number,value:string){const lines=[...config.lines];lines[index]=value.replace(/[\r\n]/g,' ');edit({lines});}
 function move(index:number,delta:number){const lines=[...config.lines];[lines[index],lines[index+delta]]=[lines[index+delta],lines[index]];edit({lines});}
 async function copy(){try{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setNotice(t("请选择下面的地址并复制。"));}}
 async function save(format:'png'|'gif'|'webp'){if(busy)return;setBusy(format);setProgress(0);const abort=new AbortController();exportAbort.current=abort;const snapshot=structuredClone(config);try{await loadFont(snapshot.font);let blob:Blob;if(format==='png'){const canvas=document.createElement('canvas');drawFrame(canvas,snapshot,buildLayers(snapshot),snapshot.transition+.1,active);blob=await canvasBlob(canvas,'image/png');}else blob=await exportAnimation(snapshot,format,setProgress,abort.signal);if(abort.signal.aborted)return;downloadBlob(blob,`typecast-${Date.now()}.${format}`);setNotice(`${format.toUpperCase()} ${t("文件已生成。")}`);}catch(e){if(e instanceof Error&&e.name!=='AbortError')setNotice(t(e.message));}finally{setBusy('');exportAbort.current=null;}}
 const validLines=config.lines.filter(s=>s.trim()),canExport=loaded&&config.visible&&validLines.length>0;
 return <div className="studio-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark"><Type size={23}/></span><div><strong>Typecast <span>Studio</span></strong><small>{t("中文直播花字工具")}</small></div></div><label className="language-picker"><span>Language / 언어 / 语言</span><NativeSelect aria-label="Language / 언어 / 语言" value={config.language} disabled={!loaded} onChange={e=>edit({language:e.target.value})}>{LANGUAGES.map(([id,name])=><option key={id} value={id}>{name}</option>)}</NativeSelect></label><div className={'connection '+(connected?'online':'offline')}><i/>{connected?t("本地已连接"):t("正在连接后台")}</div><a className="help-link" href="#douyin-guide"><Monitor size={17}/> {t("直播伴侣连接")}</a></header>
  <main className="workspace">
   <section className="editor-panel"><div className="section-heading"><div><span className="eyebrow">{t("专为你的直播画面")}</span><h1>{t("好看的字，即刻上屏。")}</h1></div><span className="small-icon"><SlidersHorizontal size={21}/></span></div>
    <fieldset disabled={!loaded} className="editor-fields">
    <section className="control-section"><div className="section-label"><h2>{t("直播文案")}</h2><span>{config.lines.length} / 8</span></div><p className="hint">{t("一格一句。支持单条常驻，也支持多条轮播。")}</p>
     <div className="line-list">{config.lines.map((line,i)=><div className={'line-card '+(i===active?'current':'')} key={i}><div className="line-top"><span className="line-number">{String(i+1).padStart(2,'0')}</span><span>{i===active?t("当前预览"):t("待播放")}</span><div className="line-actions"><Button variant="ghost" size="icon-sm" aria-label={`${t("上移")} ${i+1}`} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp/></Button><Button variant="ghost" size="icon-sm" aria-label={`${t("下移")} ${i+1}`} disabled={i===config.lines.length-1} onClick={()=>move(i,1)}><ArrowDown/></Button><Button variant="ghost" size="icon-sm" aria-label={`${t("删除")} ${i+1}`} disabled={config.lines.length===1} onClick={()=>edit({lines:config.lines.filter((_,j)=>j!==i)})}><Trash2/></Button></div></div><Input aria-label={`${t("直播文案")} ${i+1}`} className="line-input" value={line} maxLength={160} onChange={e=>lineChange(i,e.target.value)} placeholder={t("输入要在直播中显示的文字")}/><span className="char-count">{line.length} / 160</span></div>)}</div>
     <Button variant="outline" className="add-line" disabled={config.lines.length>=8} onClick={()=>edit({lines:[...config.lines,'']})}><Plus/> {t("添加文案")}</Button>
    </section>
    <section className="control-section"><div className="section-label"><h2>{t("花字样式 · 14 款")}</h2><Sparkles size={17}/></div><div className="style-grid">{STYLES.map(({id,name,sample})=><button key={id} className={'style-tile '+id+' '+(config.style===id?'selected':'')} aria-pressed={config.style===id} onClick={()=>edit(presetSettings(id))}><b>{t(sample)}</b><span>{t(name)}</span>{config.style===id&&<Check size={13}/>}</button>)}</div>
     <label htmlFor="font-family" className="resolution-row font-row">{t("字体")}<NativeSelect id="font-family" value={config.font} onChange={e=>edit({font:e.target.value})}><option value="sans">{t("思源黑体 · 醒目厚重")}</option><option value="serif">{t("思源宋体 · 精致优雅")}</option></NativeSelect></label>{config.style==='custom'&&<label className="color-row">{t("文字颜色")}<input aria-label={t("文字颜色")} type="color" value={config.color} onChange={e=>edit({color:e.target.value})}/><code>{config.color}</code></label>}
     <div className="range-grid"><Range label={t("字号上限")} value={config.fontSize} min={24} max={140} unit=" px" onChange={fontSize=>edit({fontSize})}/><Range label={t("描边")} value={config.stroke} min={0} max={8} step={.5} unit=" px" onChange={stroke=>edit({stroke})}/><Range label={t("立体深度")} value={config.depth} min={0} max={8} unit=" px" onChange={depth=>edit({depth})}/><Range label={t("发光强度")} value={config.glow} min={0} max={24} unit=" px" onChange={glow=>edit({glow})}/></div>
     <div className="inline-controls"><label className="color-row">{t("描边颜色")}<input aria-label={t("描边颜色")} type="color" value={config.outline} onChange={e=>edit({outline:e.target.value})}/></label><label htmlFor="highlight" className="switch-label">{t("突出联系方式")}<Switch id="highlight" checked={config.highlight} onCheckedChange={highlight=>edit({highlight})}/></label></div>
     <p className="hint small">{t("长句自动缩小以适应画面，始终保持一行。")}</p>
    </section>
    <section className="control-section"><div className="section-label"><h2>{t("动画与画面")}</h2><Radio size={17}/></div><div className="select-grid"><label htmlFor="animation">{t("动画效果")}<NativeSelect id="animation" value={config.animation} onChange={e=>edit({animation:e.target.value})}>{ANIMATIONS.map(([value,label])=><option key={value} value={value}>{t(label)}</option>)}</NativeSelect></label><label htmlFor="alignment">{t("文字对齐")}<NativeSelect id="alignment" value={config.align} onChange={e=>edit({align:e.target.value})}><option value="left">{t("左对齐")}</option><option value="center">{t("居中")}</option><option value="right">{t("右对齐")}</option></NativeSelect></label></div>
     <label htmlFor="single-mode" className="resolution-row single-mode">{t("单条文案")}<NativeSelect id="single-mode" value={config.singleMode} onChange={e=>edit({singleMode:e.target.value})}><option value="stay">{t("入场后常驻（呼吸 / 滚动持续播放）")}</option><option value="loop">{t("按所选效果循环播放")}</option></NativeSelect></label><p className="hint small">{t("只有一条也能使用。多条文案自动轮播，每次只显示一条。")}</p><div className="range-grid"><Range label={t("停留时间")} value={config.hold} min={1} max={10} step={.1} unit={t("秒")} onChange={hold=>edit({hold})}/><Range label={t("入场 / 离场")} value={config.transition} min={.15} max={1} step={.05} unit={t("秒")} onChange={transition=>edit({transition})}/></div><label htmlFor="resolution" className="resolution-row">{t("输出尺寸")}<NativeSelect id="resolution" value={`${config.width}x${config.height}`} onChange={e=>{const [width,height]=e.target.value.split('x').map(Number);edit({width,height});}}><option value="1200x176">{t("1200 × 176 · 标准")}</option><option value="1600x240">{t("1600 × 240 · 加宽")}</option><option value="1920x280">{t("1920 × 280 · 全宽")}</option></NativeSelect></label>
    </section></fieldset>
   </section>
   <section className="broadcast-panel"><div className="preview-heading"><div><span className="live-tag"><i/> {t("实时预览")}</span><h2>{t("看看你的直播花字")}</h2></div><span className="size-tag">{config.width} × {config.height}</span></div>
    <div className={'preview-stage '+backdrop}><div className="safe-corner tl"/><div className="safe-corner tr"/><div className="safe-corner bl"/><div className="safe-corner br"/><Preview config={config} paused={paused} restart={restart} onLine={setActive}/>{(!validLines.length||!config.visible)&&<span className="empty-preview">{config.visible?t("请先输入一条文案"):t("字幕已隐藏")}</span>}<span className="transparency-note">{t("透明背景 · 棋盘格不会被导出")}</span></div>
    <div className="preview-toolbar"><div className="preview-buttons"><Button variant="ghost" size="icon" aria-label={paused?t("播放预览"):t("暂停预览")} onClick={()=>setPaused(!paused)}>{paused?<Play/>:<Pause/>}</Button><Button variant="ghost" size="icon" aria-label={t("重新播放预览")} onClick={()=>setRestart(r=>r+1)}><RotateCcw/></Button><span>{validLines.length?active+1:0} <em>/ {validLines.length}</em></span></div><div className="background-picker"><span>{t("检查底色")}</span>{['checker','dark-bg','light-bg'].map(b=><button key={b} className={b+' '+(backdrop===b?'picked':'')} aria-label={{checker:t("棋盘格"), 'dark-bg':t("深色背景"),'light-bg':t("浅色背景")}[b]} aria-pressed={backdrop===b} onClick={()=>setBackdrop(b)}/>)}</div></div>
    <section className="obs-card" id="douyin-guide"><div className="obs-title"><span className="obs-icon"><Monitor size={23}/></span><div><h2>{t("连接抖音直播伴侣")}</h2><p>{t("捕获独立字幕窗口，修改文案后实时更新。")}</p></div></div>
     <div className="capture-controls"><label htmlFor="capture-key">{t("抠图底色")}<NativeSelect id="capture-key" value={captureKey} onChange={e=>setCaptureKey(e.target.value)}><option value="green">{t("纯绿 #00FF00")}</option><option value="blue">{t("纯蓝 #0000FF")}</option><option value="black">{t("纯黑（不抠图）")}</option></NativeSelect></label><Button disabled={!loaded||opening} onClick={async()=>{setOpening(true);try{const r=await fetch('/api/capture-window',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:captureKey})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||t("无法打开字幕窗口。"));setNotice(t("字幕窗口已打开，请在直播伴侣中添加窗口素材。"));}catch(e){setNotice(e instanceof Error?t(e.message):t("打开失败，请尝试手动链接。"));}finally{setOpening(false);}}}><ExternalLink/>{opening?t("正在打开…"):t("打开字幕窗口")}</Button></div>
     <ol className="obs-steps"><li><b>1</b><span>{t("点击上方按钮")}<br/><strong>{t("打开独立字幕窗口")}</strong></span></li><li><b>2</b><span>{t("直播伴侣")}{" "}<strong>{t("添加素材 → 窗口")}</strong><br/>{t("选择“字幕输出 - Typecast Studio”")}</span></li><li><b>3</b><span>{t("素材设置中")}{" "}<strong>{t("绿幕抠图")}</strong><br/>{t("吸取底色，裁去标题栏")}</span></li></ol>
     <p className="hint small">{t("绿色文字建议用蓝底，蓝色文字建议用绿底。抠图入口随伴侣版本可能不同；若当前窗口素材没有抠图选项，可先使用黑底或导出 PNG。不要最小化或关闭字幕窗口。")}</p>
     <details className="connection-details"><summary>{t("手动链接 / 透明网页输出")}</summary><p className="hint">{t("字幕窗口手动链接（先在浏览器打开，再捕获窗口）：")}</p><input readOnly aria-label={t("字幕窗口手动链接")} value={location.origin+'/capture?key='+captureKey} onFocus={e=>e.target.select()}/><p className="hint">{t("下面的透明链接仅供支持网页源的软件使用，不要求直播伴侣有网页源入口。")}</p><div className="url-box"><input aria-label={t("透明字幕链接")} readOnly value={link} onFocus={e=>e.target.select()}/><Button onClick={copy}>{copied?<Check/>:<Copy/>}{copied?t("已复制"):t("复制链接")}</Button></div><a href="/overlay" target="_blank" rel="noreferrer">{t("打开透明输出")}<ExternalLink size={14}/></a></details>
     <div className="obs-bottom"><a href="https://streamingtool.douyin.com/docs/guide_ztb12xj7" target="_blank" rel="noreferrer">{t("官方抠图说明")}<ExternalLink size={14}/></a><span>{t("后台程序与直播伴侣须在同一台电脑运行。")}</span></div>
    </section>
    <section className="on-air-card"><div><span className={'status-dot '+(config.visible?'':'off')}/><div><strong>{config.visible?t("字幕显示中"):t("字幕已隐藏")}</strong><span>{t("对已连接的直播字幕生效")}</span></div></div><Switch aria-label={t("显示字幕")} checked={config.visible} disabled={!loaded} onCheckedChange={visible=>edit({visible})}/></section>
    <section className="export-card"><div className="section-label"><h2><Download size={17}/> {t("也可以下载文件")}</h2><span>{t("透明背景")}</span></div><div className="export-buttons"><Button variant="outline" disabled={!canExport||!!busy} onClick={()=>save('webp')}>{t("导出 WebP")}<span>{t("推荐")}</span></Button><Button variant="outline" disabled={!canExport||!!busy} onClick={()=>save('gif')}>{t("导出 GIF")}</Button><Button variant="ghost" disabled={!canExport||!!busy} onClick={()=>save('png')}>{t("当前文案 PNG")}</Button></div><p className="hint small">{t("WebP 保留柔和透明边缘；GIF 兼容性更广。单条常驻的入场动画只播放一次。")}</p>{busy&&<output className="export-progress"><progress max={100} value={progress}/><span>{busy.toUpperCase()} {progress}%</span><Button variant="ghost" onClick={()=>exportAbort.current?.abort()}>{t("取消")}</Button></output>}</section>
    <output className={'save-status '+(status==='error'?'error':'')}>{status==='error'?<AlertCircle size={15}/>:status==='synced'?<Check size={15}/>:<Radio size={15}/>}<span>{!connected?t("正在连接后台。请从开始菜单运行“直播花字工作室”。"):status==='synced'?t("全部修改已保存，并同步到字幕输出。"):status==='saving'?t("正在保存并同步字幕…"):status==='editing'?t("输入结束后自动保存与同步。"):t(error)||t("正在读取设置…")}</span>{status==='error'&&<Button variant="ghost" onClick={flush}>{t("重试")}</Button>}</output>
   </section>
  </main><footer>TYPECAST STUDIO <span>{t("Windows · 本地运行 · 无需账号")}</span></footer>{notice&&<output className="toast">{notice}</output>}
 </div>;
}
