import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright-core';
if(process.env.GITHUB_ACTIONS!=='true'||process.platform!=='win32')throw new Error('Windows CI only');
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1024,height:768}});
 const failures=[];page.on('pageerror',e=>failures.push(e.message));
 await page.goto('http://localhost:4318');
 await page.waitForFunction(()=>!document.querySelector('fieldset')?.disabled);
 assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN');
 assert.equal(await page.locator('.language-picker').count(),0);
 await page.getByRole('heading',{name:'直播文案',exact:true}).waitFor();
 assert.equal(await page.locator('.line-input').count(),1);
 const sentence='欢迎来到直播间，微信：your_wechat';
 await page.locator('.line-input').first().fill(sentence);
 await page.getByRole('button',{name:'添加文案',exact:true}).click();
 assert.equal(await page.locator('.line-input').count(),2);
 await page.locator('.line-input').nth(1).fill('第二条文案，QQ：123456789');
 await page.getByRole('button',{name:'删除 2',exact:true}).click();
 assert.equal(await page.locator('.line-input').count(),1);
 assert.equal(await page.locator('.line-input').first().inputValue(),sentence);
 await page.locator('#effect').selectOption('fire');
 await page.waitForFunction(async text=>{const s=await(await fetch('/api/state')).json();return s.config.lines.length===1&&s.config.lines[0]===text&&!s.config.highlight&&s.config.effect==='fire';},sentence);
 await mkdir('work/ui',{recursive:true});
 const output=await browser.newPage();await output.goto('http://localhost:4318/capture?key=green');
 await output.waitForFunction(()=>document.title==='字幕输出 - Typecast Studio');
 await page.evaluate(()=>document.fonts.ready);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false,'Default editor must fit one 1024x768 screen');
 assert.equal(await output.locator('.overlay-surface').evaluate(n=>getComputedStyle(n).backgroundColor),'rgba(0, 0, 0, 0)');
 await output.screenshot({path:'work/ui/transparent-output.png',omitBackground:true});
 await mkdir('work/ui',{recursive:true});
 await page.screenshot({path:'work/ui/editor-zh-CN.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:760,height:1040});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.getByRole('button',{name:'退出程序',exact:true}).click();
 await page.getByRole('heading',{name:'程序已退出',exact:true}).waitFor();
 assert.deepEqual(failures,[]);
 console.log('PASS: Chinese-only simple UI, one entry, add/delete, uniform color, output, and web Quit.');
}finally{await browser.close();}
