LangString WelcomeTitle ${LANG_ENGLISH} "Welcome to Typecast Studio"
LangString WelcomeTitle ${LANG_KOREAN} "Typecast Studio 설치를 시작합니다"
LangString WelcomeTitle ${LANG_SIMPCHINESE} "欢迎安装 Typecast Studio"
LangString WelcomeText ${LANG_ENGLISH} "Create live text effects with 14 styles and 10 animations. Use one text entry or rotate several.$\r$\n$\r$\nEverything is included. You do not need to install Node.js or any developer tools.$\r$\n$\r$\nProgram files go in Program Files. Your settings stay in your user AppData folder. Please exit the previous version before upgrading."
LangString WelcomeText ${LANG_KOREAN} "14가지 디자인과 10가지 애니메이션으로 방송 문구를 꾸미세요. 문구 하나 또는 여러 문구의 순차 재생을 지원합니다.$\r$\n$\r$\n실행 환경이 포함되어 Node.js나 개발 도구를 따로 설치할 필요가 없습니다.$\r$\n$\r$\n프로그램은 Program Files에 설치하고 설정은 사용자 AppData에 보관합니다. 업데이트 전에 이전 버전을 종료하세요."
LangString WelcomeText ${LANG_SIMPCHINESE} "包含 14 款样式、10 种动画，支持单条文案或多条轮播。$\r$\n$\r$\n已包含运行环境，无需另装 Node.js 或开发工具。$\r$\n$\r$\n程序安装到 Program Files，设置保存在用户 AppData。升级前请退出旧版本。"
LangString FinishTitle ${LANG_ENGLISH} "Installation complete"
LangString FinishTitle ${LANG_KOREAN} "설치 완료"
LangString FinishTitle ${LANG_SIMPCHINESE} "安装完成"
LangString FinishText ${LANG_ENGLISH} "Open Typecast Studio from your desktop or Start menu.$\r$\n$\r$\nIf enabled, the background service starts when you sign in, without opening a browser.$\r$\n$\r$\nChoose English, Korean or Chinese in the editor. The Start menu includes user guides and a shortcut to stop the background service."
LangString FinishText ${LANG_KOREAN} "바탕화면이나 시작 메뉴에서 Typecast Studio를 실행하세요.$\r$\n$\r$\n자동 시작을 선택하면 로그인 시 브라우저를 띄우지 않고 백그라운드 서비스만 실행합니다.$\r$\n$\r$\n편집기에서 영어·한국어·중국어를 선택할 수 있습니다. 시작 메뉴에는 사용 설명서와 백그라운드 종료 바로가기가 있습니다."
LangString FinishText ${LANG_SIMPCHINESE} "从桌面或开始菜单打开 Typecast Studio。$\r$\n$\r$\n启用自动启动后，登录时仅启动后台服务，不弹出浏览器。$\r$\n$\r$\n编辑器可选择英语、韩语或中文。开始菜单提供使用说明和退出后台服务的快捷方式。"
LangString Need64 ${LANG_ENGLISH} "This version requires 64-bit Windows."
LangString Need64 ${LANG_KOREAN} "64비트 Windows가 필요합니다."
LangString Need64 ${LANG_SIMPCHINESE} "此版本需要 64 位 Windows。"
LangString CoreFiles ${LANG_ENGLISH} "Program files (required)"
LangString CoreFiles ${LANG_KOREAN} "프로그램 파일 (필수)"
LangString CoreFiles ${LANG_SIMPCHINESE} "程序文件（必需）"
LangString StartupOption ${LANG_ENGLISH} "Start automatically when I sign in (recommended)"
LangString StartupOption ${LANG_KOREAN} "Windows 로그인 시 자동 시작 (권장)"
LangString StartupOption ${LANG_SIMPCHINESE} "登录 Windows 后自动启动（推荐）"
LangString DesktopOption ${LANG_ENGLISH} "Create a desktop shortcut"
LangString DesktopOption ${LANG_KOREAN} "바탕화면 바로가기 만들기"
LangString DesktopOption ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString StopService ${LANG_ENGLISH} "Stop background service"
LangString StopService ${LANG_KOREAN} "백그라운드 서비스 종료"
LangString StopService ${LANG_SIMPCHINESE} "退出后台服务"
LangString UserGuide ${LANG_ENGLISH} "User guide"
LangString UserGuide ${LANG_KOREAN} "사용 설명서"
LangString UserGuide ${LANG_SIMPCHINESE} "使用说明"
LangString UninstallLabel ${LANG_ENGLISH} "Uninstall"
LangString UninstallLabel ${LANG_KOREAN} "제거"
LangString UninstallLabel ${LANG_SIMPCHINESE} "卸载"
LangString LaunchError ${LANG_ENGLISH} "Could not start Typecast Studio. Exit the previous version and check that port 4318 is free.$\r$\n$\r$\nDetails: $LOCALAPPDATA\Typecast Studio\startup-error.log"
LangString LaunchError ${LANG_KOREAN} "Typecast Studio를 시작하지 못했습니다. 이전 버전을 종료하고 4318 포트가 비어 있는지 확인하세요.$\r$\n$\r$\n오류 기록: $LOCALAPPDATA\Typecast Studio\startup-error.log"
LangString LaunchError ${LANG_SIMPCHINESE} "程序无法启动。请退出旧版本并确认 4318 端口未被占用。$\r$\n$\r$\n详细记录：$LOCALAPPDATA\Typecast Studio\startup-error.log"
